version: "2"
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    network_mode: "host"
 
  ds-dashboard:
    image: ds-dashboard:prod
    ports:
      - "4200:80"
  ml_user:
    image: ml_user:1.0-SNAPSHOT-abtesting
    ports:
      - "9000:9000"
    network_mode: "host"
    depends_on:
      - kafka
  rendezvous:
    image: brain_server:1.0-SNAPSHOT-abtesting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9001:9001"
    network_mode: "host"
    environment:
      - APPLICATION_SECRET=INSERT_YOUR_SECRET
    depends_on:
      - kafka

networks:
  custom_network:
    external : true
  

